spring.application.name=sigortapp-portal-backend
server.port=8080

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sigorta
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
app.jwt.secret=change-this-secret-key-for-production-use-at-least-32-bytes-long
app.jwt.expiration-ms=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=senin.mailin@gmail.com
spring.mail.password=16_haneli_uygulama_sifren
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
